-- SQLite
-- Faça uma consulta que retorna o nome do passageiro, a data do vôo (FlightDate), e o
-- AirportCode da Origem e Destino dos vôos de cada passageiro. Os nomes das
-- colunas do ID do aeroporto devem ser Origem e Destino, respectivamente.
